# Generated by Django 3.2 on 2023-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del color')),
                ('codigo_hexadecimal', models.CharField(max_length=7, unique=True, verbose_name='Código hexadecimal del color')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción del color')),
            ],
            options={
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('capital', models.CharField(max_length=25, verbose_name='Capital')),
                ('region', models.CharField(max_length=25, verbose_name='Región')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
    ]
