# Generated by Django 3.2 on 2023-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codigo_hexadecimal',
            field=models.CharField(max_length=7, verbose_name='Código hexadecimal del color'),
        ),
    ]
