# Generated by Django 3.2 on 2023-04-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=25, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo Apellido')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('cod_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.provincia', verbose_name='Provincia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
