# Generated by Django 3.2 on 2023-04-29 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('nom_cientifico', models.CharField(max_length=50, unique=True, verbose_name='Nombre Científico')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('origen', models.CharField(blank=True, max_length=25, null=True, verbose_name='Origen')),
                ('peso_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Peso Promedio')),
                ('altura_media', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Altura Promedio')),
                ('longevidad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Esperanza de vida')),
                ('actividad', models.CharField(max_length=5, verbose_name='Nivel de Actividad')),
                ('temperamento', models.CharField(max_length=20, verbose_name='Temperamento')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katapp.especie', verbose_name='Especie')),
            ],
        ),
        migrations.CreateModel(
            name='MLost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('lugar_perdida', models.CharField(max_length=255, verbose_name='Lugar Pérdida')),
                ('foto', models.CharField(max_length=80, verbose_name='Foto')),
                ('descripcion', models.TextField(max_length=255, verbose_name='Descripción')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo')),
                ('anio_nacimiento', models.CharField(blank=True, max_length=4, null=True, verbose_name='Año de nacimiento')),
                ('fecha_extravio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha extravío')),
                ('tamano', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tamaño')),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Peso')),
                ('num_chip', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Número de Chip')),
                ('pelo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Pelo')),
                ('collar', models.BooleanField(default=False)),
                ('devuelto', models.BooleanField(default=False)),
                ('color', models.ManyToManyField(related_name='mlosts_colors', to='common.Color', verbose_name='Color')),
                ('datos_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Datos de Contacto')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katapp.especie', verbose_name='Especie')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katapp.raza', verbose_name='Raza')),
            ],
        ),
        migrations.CreateModel(
            name='MFind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre')),
                ('lugar_encontrado', models.CharField(max_length=255, verbose_name='Lugar Encontrado')),
                ('foto', models.CharField(max_length=80, verbose_name='Foto')),
                ('descripcion', models.TextField(max_length=255, verbose_name='Descripción')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo')),
                ('fecha_encontrado', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha encontrado')),
                ('tamano', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tamaño')),
                ('num_chip', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Número de Chip')),
                ('pelo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Pelo')),
                ('collar', models.BooleanField(default=False)),
                ('devuelto', models.BooleanField(default=False)),
                ('color', models.ManyToManyField(related_name='mfinds_colors', to='common.Color', verbose_name='Color')),
                ('datos_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Datos de Contacto')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katapp.especie', verbose_name='Especie')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='katapp.raza', verbose_name='Raza')),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aviso', models.CharField(max_length=20, verbose_name='Tipo de aviso')),
                ('fecha_aviso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de aviso')),
                ('hora_aviso', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de aviso')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('imagen', models.CharField(max_length=80, verbose_name='Imagen')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contacto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.provincia', verbose_name='Provincia')),
            ],
        ),
    ]
