# Generated by Django 3.2 on 2023-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katapp', '0002_auto_20230429_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'verbose_name_plural': 'Avisos'},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterModelOptions(
            name='mfind',
            options={'verbose_name_plural': 'Mascotas encontradas'},
        ),
        migrations.AlterModelOptions(
            name='mlost',
            options={'verbose_name_plural': 'Mascotas Perdidas'},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'verbose_name_plural': 'Razas'},
        ),
        migrations.AddField(
            model_name='aviso',
            name='descripcion',
            field=models.TextField(default='Descripción', max_length=255, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aviso',
            name='razon',
            field=models.CharField(default='Razón aviso', max_length=20, verbose_name='Razón'),
            preserve_default=False,
        ),
    ]
