# Generated by Django 3.2 on 2023-05-05 17:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katapp', '0004_auto_20230430_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlost',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='altura_media',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Altura Promedio'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='longevidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Esperanza de vida'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='peso_medio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Peso Promedio'),
        ),
    ]
