# Generated by Django 3.2 on 2023-05-13 15:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katapp', '0005_auto_20230505_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='imagen',
            field=models.ImageField(max_length=80, upload_to='m_lost_fotos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mfind',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='mfind',
            name='foto',
            field=models.ImageField(max_length=80, upload_to='m_lost_fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='mlost',
            name='foto',
            field=models.ImageField(max_length=80, upload_to='m_lost_fotos/', verbose_name='Foto'),
        ),
    ]
